#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Module for reading metadata files generated by rsync with --filesfrom option.

This module provides functionality to parse binary metadata files that contain
file system information including filenames, inodes, permissions, timestamps,
and other stat-like data.

Classes:
    Reader: Main class for reading and iterating through metadata entries

Functions:
    read_int_le: Read little-endian integers from binary data
    read_string: Read length-prefixed strings from binary data  
    read_char: Read single character from binary data
    main: Command-line interface for the module

Usage:
    python metareader.py <metadata_file>
    
    Or import as module:
    reader = Reader('metadata.bin')
    for entry in reader:
        print(entry)   
"""

from typing import NamedTuple, Callable, BinaryIO, Any

__FILETYPE__ = 'RSYNC-INO'

FieldTypes = NamedTuple('FieldTypes', 
    [('name', str),
     ('type', str)]
)


data_fields = {
    'N': FieldTypes('filename', 'string'),
    'd': FieldTypes('st_dev', 'uint64_t'),
    'T': FieldTypes('type', 'char'),
    'i': FieldTypes('st_ino', 'uint64_t'),
    'M': FieldTypes('st_mode', 'uint32_t'),
    'n': FieldTypes('st_nlink', 'uint64_t'),
    'u': FieldTypes('st_uid', 'uint32_t'),
    'g': FieldTypes('st_gid', 'uint32_t'),
    'r': FieldTypes('st_rdev', 'uint64_t'),
    's': FieldTypes('st_size', 'int64_t'),
    'B': FieldTypes('st_blksize', 'int64_t'),
    'b': FieldTypes('st_blocks', 'int64_t'),
    'a': FieldTypes('st_atime', 'int64_t'),
    'c': FieldTypes('st_ctime', 'int64_t'),
    'm': FieldTypes('st_mtime', 'int64_t'),
}


def read_int_le(fp, type: str):
    """Read an integer of specified type from file pointer in little-endian format."""
    int_fmt = {'uint32_t': (4, False) , 
               'int32_t': (4, True), 
               'uint64_t': (8, False), 
               'int64_t': (8, True)}
    bytes, signed = int_fmt[type]
    bytes_read = fp.read(bytes)
    if len(bytes_read) != bytes:
        raise EOFError(f"Unexpected end of file while reading {type}")
    return int.from_bytes(bytes_read, byteorder='little', signed=signed)


def read_string(fp):
    """Read a length-prefixed string from file pointer."""
    length = read_int_le(fp, 'uint32_t')
    str_bytes = fp.read(length)
    if len(str_bytes) != length:
        raise EOFError("Unexpected end of file while reading string")
    return str_bytes.decode('utf-8')


def read_char(fp):
    """Read a single character from file pointer."""
    char_byte = fp.read(1)
    if len(char_byte) != 1:
        raise EOFError("Unexpected end of file while reading char")
    return char_byte.decode('utf-8')


class Reader:
    """Class to read metadata from a metadata file.
    
    File header information is read on initialization, and the class is iterable to yield
    metadata dictionaries for each file.
    """
    def __init__(self, file_path):
        self.file_path = file_path
        #self.version = None
        #self.topdir = None
        #self.fmt = None
        #self._data_start = None
        self.header = self.get_header(file_path)

    def reader_factory(type: str) -> Callable[[BinaryIO], Any]:
        """Factory function to return the appropriate reader function based on type."""
        if type == 'string':
            return read_string
        elif type == 'char':
            return read_char
        elif type in ('uint32_t', 'int32_t', 'uint64_t', 'int64_t'):
            return lambda fp, t=type: read_int_le(fp, t)
        else:
            raise ValueError(f"Unsupported field type: {type}")

    def get_header(self, reread: bool = False) -> dict:
        """Get the header information from the metadata file."""
        if hasattr(self, 'header') and not reread:
            return self.header
        header = {}
        with open(self.file_path, 'rb') as fp:
            # Check file type
            header['filetype'] = read_string(fp)
            if header['filetype'] != __FILETYPE__:
                raise ValueError(f"Invalid file type: {header['filetype']}")
            header['version'] = read_int_le(fp, 'uint32_t')
            # Read header based on version
            if header['version'] == 1:
                # Version 1 header format
                header['str'] = read_string(fp)
                header['fmt'] = read_string(fp)
                header['data_start'] = fp.tell()
            else:
                raise ValueError(f"Unsupported version: {header['version']}")       
        return header       

    def __iter__(self) -> dict:
        """Iterator yielding Dict of (name, value) key-value pairs of file metadata."""
        with open(self.file_path, 'rb') as fp:
            fp.seek(self.header['data_start'])
            while True:
                try:
                    metadata = {}
                    for field in self.header['fmt']:
                        field_data = Reader.reader_factory(data_fields[field].type)(fp)
                        metadata[data_fields[field].name] = field_data
                    yield metadata
                except EOFError:
                    break  # EOF

    def __repr__(self):
        return f"<Reader file='{self.file_path}', type='{self.header['filetype']}'" \
               + f" version={self.header['version']} str='{self.header['str']}'>"
    
    def __str__(self):
        return self.__repr__()
    
    def read_all(self) -> list:
        """Read all metadata entries and return as a list of dictionaries."""
        return list(self.__iter__())

def main():
    """module test"""
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python metareader.py <metadata_file>")
        sys.exit(1)
    
    file = sys.argv[1]
    print(f"Reading metadata from file: {file}\n")
    reader = Reader(file)

    print(f"Metadata: {reader}")
    for metadata in reader:
        print(f" - {metadata}")


if __name__ == "__main__":
    main()